//#region LOGIN
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";


//#endregion

//#region ROUTING
export const GET_ROUTING = "GET_ROUTING";
export const GET_ROUTING_SUCCESS = "GET_ROUTING_SUCCESS";
export const GET_ROUTING_ERROR = "GET_ROUTING_ERROR";

export const GET_UPDATEROUTING = "GET_UPDATEROUTING";
export const UPDATE_ROUTING = "UPDATE_ROUTING";
export const UPDATE_ROUTING_SUCCESS = "UPDATE_ROUTING_SUCCESS";
export const UPDATE_ROUTING_ERROR = "UPDATE_ROUTING_ERROR";
//#endregion

//#region INCIDENTS
export const ADD_INCIDENT = "ADD_INCIDENT";
export const ADD_INCIDENT_SUCCESS = "ADD_INCIDENT_SUCCESS";
export const ADD_INCIDENT_ERROR = "ADD_INCIDENT_ERROR";
//#endregion


//#region LOGIN
export const UPDATE_AUTH = "UPDATE_AUTH";
export const UPDATE_AUTH_SUCCESS = "UPDATE_AUTH_SUCCESS";
export const UPDATE_AUTH_ERROR = "UPDATE_AUTH_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SET_USER = "SET_USER";

export const CERRAR_SESSION = "CERRAR_SESSION";
//#endregion